package prac2;

import java.awt.Color;
import java.awt.FlowLayout;
import java.time.LocalDateTime;
import java.util.*;
import javax.swing.JFrame;

public class Reloj extends JFrame {
    String hora, minutos, segundos, ampm;
    Calendar calendario;
    LocalDateTime locaDate = LocalDateTime.now();
    int hours  = locaDate.getHour();
    int minutes = locaDate.getMinute();
    int seconds = locaDate.getSecond();
    Relojcito relojcito1;
    Relojcito relojcito2;
    Relojcito relojcito3;
    Relojcito relojcito4;

    /*Thread h1;
    Thread h2;
    Thread h3;
    Thread h4;
*/
    
    public Reloj() {
        this.relojcito1 = new Relojcito();
        Thread h1 = new Thread(relojcito1);
        this.add(relojcito1);
        
        this.relojcito2 = new Relojcito("random");
        Thread h2 = new Thread(relojcito2);
        this.add(relojcito2);
        
        this.relojcito3 = new Relojcito("random");
        Thread h3 = new Thread(relojcito3);
        this.add(relojcito3);
        
        this.relojcito4 = new Relojcito("random");
        Thread h4 = new Thread(relojcito4);
        this.add(relojcito4);
       
        this.setLayout(new FlowLayout());
        this.getContentPane().setBackground(Color.darkGray);
        this.setSize(310, 300);
        setLocationRelativeTo(null);
        setTitle("Reloj");
        setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        h1.start();
        h2.start();
        h3.start();
        h4.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReloj = new javax.swing.JLabel();
        lblRelojUno = new javax.swing.JLabel();
        lblRelojDos = new javax.swing.JLabel();
        lblRelojTres = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        lblReloj.setFont(new java.awt.Font("Bahnschrift", 2, 12)); // NOI18N
        lblReloj.setText("jLabel1");

        lblRelojUno.setFont(new java.awt.Font("Bahnschrift", 2, 12)); // NOI18N
        lblRelojUno.setText("jLabel1");

        lblRelojDos.setFont(new java.awt.Font("Bahnschrift", 2, 12)); // NOI18N
        lblRelojDos.setText("jLabel2");

        lblRelojTres.setFont(new java.awt.Font("Bahnschrift", 2, 12)); // NOI18N
        lblRelojTres.setText("jLabel1");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRelojTres, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblRelojUno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRelojDos)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(lblRelojUno)
                .addGap(51, 51, 51)
                .addComponent(lblRelojDos)
                .addGap(49, 49, 49)
                .addComponent(lblRelojTres)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JLabel lblRelojDos;
    private javax.swing.JLabel lblRelojTres;
    private javax.swing.JLabel lblRelojUno;
    // End of variables declaration//GEN-END:variables

}
